### ISSUE TITLE
Bug: Crucible from Ex Compressum and Wooden Buckets

### ISSUE THREAD

**Issue by Xantusia** [GalaxyOfZero/Skyfriends#1]
**Description of bug**

Trying to grab water from the Oak Crucible from Ex Compressum with Wooden Bucket from Wooden Buckets (or Edelwood Bucket from Frobidden & Arcanus) leads to transforming Wooden bucket to Water Bucket from Minecraft.

**Steps to reproduce**

Place the Oak Crucible, fill it with water (or saplings and wait), try to grab the water with Wooden bucket -> boom, you have iron water bucket from vanilla minecraft. Also with placing water with Wooden Bucket returns iron empty bucket from vanilla minecraft

**Demonstration**

https://youtu.be/c1Gv9egGDDI

**Comment by GalaxyOfZero** [comment]
I have the mod  wooden Bucket remove and the Edelwood bucket temporary disablet
