### ISSUE TITLE
Squeezer from Integrated Dynamics not accepting input

### ISSUE THREAD

**Issue by RottenMojo** [GalaxyOfZero/Skyfriends#12]
When trying to put something into the squeezer from Integrated Dynamics, it won't get put in.

Tried with coal and later with a menril log, but no luck.

**Comment by GalaxyOfZero** [comment]
i think this is not a mod problem or a pack problem. i teste this in my test world and i can not reproduce your probem. request more information since you do not use the formola from github

**Comment by RottenMojo** [comment]
Apologies, never posted an issue on github before.

I put down the squeezer, place a button in front of it. Then rightclick a menril log on it and nothing happens.

**Comment by RottenMojo** [comment]
![2022-01-20_18 51 56](https://user-images.githubusercontent.com/56158791/150394329-3831d879-ea01-4322-8a41-269f096bf630.png)

**Comment by RottenMojo** [comment]
So using a hopper to input items does work.

**Comment by GalaxyOfZero** [comment]
So i Test your report and it work all.

-  Squeezer  with hopper work, it insert i item
-  Right-click with menril log or ores also works

the only thing did i can say it work all in the pack. The Squeezer  has no problems

**Comment by RottenMojo** [comment]
If the issue can't be reproduced then you can't fix it :)

Thank you for taking the time to investigate.
