### ISSUE TITLE
[report] : Cannot craft runic altar

### ISSUE THREAD

**Issue by xdronz00** [GalaxyOfZero/Skyfriends#13]
**Describe the bug** 

I'm not able to craft runic altar using enchanting apparatus from Ars Nouveau. It says 'no recipe found'. I am pretty 
sure all the ingredients are correct (3 livingrock, 2 mana diamonds, two source buckets and source gem in the middle, see screenshot). 

 ==================================================================

**Screenshots or video**
![runic_altar_recipe](https://user-images.githubusercontent.com/17849392/150632760-33f988da-13b4-4cb4-94e9-3ce6aee5d3a7.png)

   
 ==================================================================
 - modpack Version : 1.1.5
 - Mod : Ars Nouveau and Botania
===================================================================

**Comment by GalaxyOfZero** [comment]
this is a item error with the empty space (minecraft air ), i fix this in the next update. maby today comes a fix
