### ISSUE TITLE
[Bug] : Item Router recipe error

### ISSUE THREAD

**Issue by LiXDL** [GalaxyOfZero/Skyfriends#14]
Bug Description: 
The item router in Modular Routers requires gold bars from Quark in the recipe; however, the recipe can only craft gold bars from Create Deco, while the two items are not interchangable to craft the item router. 

 ==================================================================

To reproduce the bug:
Shown in screenshots.

 ==================================================================

Screenshots:
The first two images are using craft station, and the others are directly from JEI. 

![image](https://user-images.githubusercontent.com/38141753/151691473-15e3eb8b-4f64-4ce6-bf31-1e9373fc9751.png)
![image](https://user-images.githubusercontent.com/38141753/151691501-84abd92d-c581-4772-a279-756e1fabf3ea.png)
![image](https://user-images.githubusercontent.com/38141753/151691522-42ba0207-4ed9-44f3-b307-4a52e0202006.png)
![image](https://user-images.githubusercontent.com/38141753/151691536-623570d4-645d-4d1b-b53a-73c9abc86fe4.png)

 ==================================================================
 - modpack Version : 1.1.6
 - Mod : Modular Routers, Quark, Create Deco
===================================================================

**Comment by GalaxyOfZero** [comment]
Thanks for the report, the Gold baren from Quark can your found in the Nether Fortress over all, this recipe will i fix later in the next update

**Comment by LiXDL** [comment]
Just a quick question, when crafting the Botania mana pool using Ars Nouveau enchating apparatus, the bucket will also be consumed; is that a intended outcome of the recipe? The bucket is kinda hard to make in the pack, I do hope it could be slightly easier to make the mana pool :)
