### ISSUE TITLE
[Bug] : Bucket Cast Recipe Conflict

### ISSUE THREAD

**Issue by LiXDL** [GalaxyOfZero/Skyfriends#15]
Crafting the bucket cast with smelted clay bucket will cause Tinker Construct to try to fill the bucket with liquid gold instead of making the gold bucket cast. A quick fix is to fill the clay bucket with some liquid (water for example), and then use gold to make the cast. As this tweak of crafting is not shown in JEI, I hope this issue will help. 

 ==================================================================
 - modpack Version : 1.1.7
 
===================================================================

**Comment by GalaxyOfZero** [comment]
is fix in the Quick fix Update on CurseForge :)
