### ISSUE TITLE
[report] : error loading mods 

### ISSUE THREAD

**Issue by koglulu** [GalaxyOfZero/Skyfriends#16]
**crash while loading** 

 ==================================================================

**To Reproduce**
1. Go to 'multiMC'
2. Click on 'add mod pack'
3. Search SkyFriends.'
4. Dowload
5. Launch the game

 ==================================================================

**Screenshots or video**
.
![error mod pack](https://user-images.githubusercontent.com/99329132/153237052-e0e6bcbd-3421-470a-9d53-9462f8e39372.png)

   
 ==================================================================
 - modpack Version :Last update
 - Mod : inproved Station
 - Java version : 16.0.2
![error mod pack](https://user-images.githubusercontent.com/99329132/153237867-f09439c0-93ae-4a2c-99d4-86ac06608307.png)

===================================================================
i send you the crash report too
[crash-2022-02-09_16.52.57-fml.txt](https://github.com/GalaxyOfZero/Skyfriends/files/8034050/crash-2022-02-09_16.52.57-fml.txt)

**Comment by GalaxyOfZero** [comment]
this is not a bug from my site, loade the pack agen. this is a forge during error in the load_registries event phase.

**Comment by koglulu** [comment]
maybe im unlucky ...
i try to launch like 20 time same error
i change version of forge but same error
i can only play without improved station
thx for the answer

**Comment by koglulu** [comment]
ok that works with curse forge thx
