### ISSUE TITLE
Bug?: Double crushing output

### ISSUE THREAD

**Issue by Xantusia** [GalaxyOfZero/Skyfriends#2]
**Description**

When you crush compressed (x1) cobblestone with compressed stone hammer from Ex Compressum, it returns 18 gravel (doubles amount).

**Steps to reproduce**

Well, place compressed cobblestone, break it with compressed stone hammer, get 18 gravel

**Demonstration**

https://youtu.be/X1EEsEuMheY

**Comment by GalaxyOfZero** [comment]
it's not a bug, i built it in so that you get gravel from crush compress cobble
