### ISSUE TITLE
[report] : (title)

### ISSUE THREAD

**Issue by graytoowolf** [GalaxyOfZero/Skyfriends#20]
**Describe the bug** 

(A clear and concise description of what the bug is.)
  
 ==================================================================
 - modpack Version :1.1.8
 - Mod : mekanism
===================================================================
![QQ截图20220306132308](https://user-images.githubusercontent.com/57069542/156910426-5235258f-f8e4-4ef9-8237-8c59fc65e5cc.png)

**Comment by GalaxyOfZero** [comment]
for the next time please description is your found a bug and not send only a screenshot !
