### ISSUE TITLE
How to build a level 6 altar with blood magic

### ISSUE THREAD

**Issue by graytoowolf** [GalaxyOfZero/Skyfriends#21]
**Describe the bug** 

Making the Life Bee Spawn Egg requires a blood magic level 6 altar, how should I build it. ==================================================================
 - modpack Version :1.1.9
 - Mod :Blood Magic
===================================================================
![QQ截图20220308230151](https://user-images.githubusercontent.com/57069542/157264434-961793f3-b9f5-44d1-96a1-6a2faa5eb48e.png)

**Comment by GalaxyOfZero** [comment]
yep this is a bug, but is to the same an ambiguity in the documentation of the mod, i will this fix if i have the time
