### ISSUE TITLE
Bug: missing workbench using crafts

### ISSUE THREAD

**Issue by Xantusia** [GalaxyOfZero/Skyfriends#4]
**Description of bug**

ON THE SERVER. IN SINGLEPLAYER ALL WORKS FINE. When you try to look for crafts, related to workbench using, NO recipes can be viewed. on singleplayer this recipes exist and can be viewed 

**Steps to reproduce**

Run v1.0.2 server, connect to it, try to see any workbench crafts

**Demonstration**

https://youtu.be/1UjxEDL4C8U

**Comment by GalaxyOfZero** [comment]
i fix the problem with the server and i dont no what the heck it was, if your have problems with the new server file please contact me via the SkyFriends Discore server, link is on the Curseforge SkyFriends page
